# Generated by Django 3.0.10 on 2020-10-18 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('indicador_id', models.IntegerField()),
                ('valor', models.FloatField()),
                ('espacio', models.CharField(max_length=256)),
                ('entidad', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Indicadores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256)),
                ('fuente', models.CharField(max_length=256)),
                ('g_tiempo', models.CharField(max_length=256)),
                ('g_espacio', models.CharField(max_length=256)),
                ('g_entidad', models.CharField(default='pais', max_length=256)),
                ('unidad', models.IntegerField(null=True)),
                ('data_owner', models.CharField(max_length=256, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='IndicadoresCreados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256)),
                ('formula_o', models.CharField(max_length=256)),
                ('formula', models.CharField(max_length=256)),
                ('tipo', models.CharField(max_length=256)),
                ('descripcion', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Transformaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256)),
                ('descripcion', models.CharField(blank=True, max_length=256)),
            ],
        ),
    ]
