# Generated by Django 3.0.10 on 2020-10-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicadores',
            name='indicador_id',
            field=models.IntegerField(default=0),
        ),
    ]
